[workspace]
members = ["crates/analysis", "crates/app", "crates/audio", "crates/domain", "crates/store", "crates/transcription"]
resolver = "2"

[workspace.package]
version = "0.1.16"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/Curiosity-Ai-BV/Curiosity-Transcripts"
homepage = "https://github.com/Curiosity-Ai-BV/Curiosity-Transcripts"

[workspace.lints.rust]
future-incompatible = "warn"
nonstandard-style = "warn"

[workspace.lints.clippy]
all = "warn"
