[package]
name = "curiosity-app"
version = "0.1.3"
edition = "2021"
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "curiosity_app"
path = "src/lib.rs"

[dependencies]
curiosity-analysis = { path = "../analysis" }
curiosity-audio = { path = "../audio" }
curiosity-domain = { path = "../domain" }
curiosity-store = { path = "../store" }
serde = { version = "1", features = ["derive"] }
